models:
  user:
    name:
      max_size: 50
    email:
      max_size: 255
    password:
      min_size: 6
  book:
    title_max_len: 100
    descrip_max_len: 400
    author_name_max_len: 50
    self_per_page: 20
  review:
    content_min_len: 4
    content_max_len: 100
  request:
    title_max_len: 100
    content_min_len: 4
    content_max_len: 100
    self_per_page: 5

view:
  user:
    size:
      max_size: 50

controllers:
  reviews:
    per_page: 20
  books:
    per_page: 5
    per_page_search: 12
  admin:
    books:
      per_page: 10
    requests:
      per_page: 10
    reviews:
      per_page: 10
    users:
      per_page: 10


