models:
  user:
    name:
      max_size: 50
    email:
      max_size: 255
    password:
      min_size: 6
  book:
    title_max_len: 100
    descrip_max_len: 400
    author_name_max_len: 50
  review:
    content_min_len: 4
    content_max_len: 100

view:
  user:
    size:
      max_size: 50
